### ISSUE TITLE
Problem with campell

### ISSUE THREAD

**Issue by zhangtopus** [OpenFAST/matlab-toolbox#36]
Dear openfast team, 
I am facing some issues with the MATLAB-toolbox for Campbell diagram. As I am completely new to this field, these issues may be superficial. Any guidance would be really helpful .

I want to see the frequency and damping of  blade without other parts of wind turbine at different wind speeds (roter speed is always 0).To do this, I set FlapDOF1=True,FlapDOF2=True, EdgeDOF=True with no other DOFs and rotor speed is always 0. Are these Settings feasible?

Another follow-up question. When I set only one blade(NumBl=1), I get some warnings from the "fx_mbc3()" function. Is there any way on how to set only one blade?

The third thing- very sorry for my clumsiness- as I turned BeamDny feature ON (CompElast=2), it is hard for me to identify the modes from one operating point to the next in the "Summary.txt" file with the wind speeds up. And Compared with ED , no blade changes are visible in VTK files with BeamDny feature ON. I don't sure if it's my setup or the program. Any suggestions/guidance?
![图片1](https://user-images.githubusercontent.com/97727163/166911507-7c39e3ba-1f7a-4c45-a9dd-5de9fb15185c.png)

**Comment by jjonkman** [comment]
Dear @zhangtopus,

Yes, your settings are reasonable to determine the natural frequencies of an isolated blade.

Please note that unless `NumBl` = 1 in ElastoDyn, the eigensolution will report duplicated values for each blade mode (one for each blade).

Moreover, the multi-blade coordinate transformation is only valid for `NumBl` = 3, hence the errors you are receiving from fx_mbc3 when `NumBl` = 1.  That said, if the rotor is not spinning, there is no reason to apply MBC3 because there are no states in the rotating frame that need to be transformed to the fixed frame when the rotor is not spinning.  Instead, when the rotor is not spinning, you can perform an eigenanalysis directly on the state matrix "A" directly output from OpenFAST.

I'm not sure I understand what issue you are running into when post-processing linearization results with BeamDyn enabled (you'll likely need to clarify what issue you have), but please note that recent improvements to BeamDyn are needed to obtain accurate linearized solutions when BeamDyn is enabled: https://github.com/OpenFAST/openfast/pull/1050.

Best regards,

**Comment by zhangtopus** [comment]
Dear @jjonkman,

Thank you for your reply.

 I get your explanation about MBC3, which is very helpful to me. I perform an eigenanalysis directly on the state matrix "A" directly output from OpenFAST as you said. It works. 

Sorry my description is not accurate enough. When settings remained unchanged  except BeamDyn feature ON, the resulting VTK file doesn't work as well as it does with ElastDyn. 
![VTK](https://user-images.githubusercontent.com/97727163/167151395-3120ddfe-d6ee-482b-bb01-e4f2d3d3be9a.gif)

Best regards,

**Comment by jjonkman** [comment]
Dear @zhangtopus,

Are you following the process outlined here to visualize the mode shapes: https://github.com/OpenFAST/r-test/blob/dev/glue-codes/openfast/5MW_Land_ModeShapes/vtk-visualization.md?

Best regards,

**Comment by zhangtopus** [comment]
Dear @jjonkman,

Thank you for your reply.I'll follow the process and try again.

Best regards,
